name: flutter_image_filter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^9.0.0
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  image: ^4.5.4
  image_picker: ^1.1.2
  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  objectbox_generator: any

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
