// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/filter_result_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 3869265884307842858),
    name: 'FilterResultModel',
    lastPropertyId: const obx_int.IdUid(5, 2132836910663006502),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4610706786180553606),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4030863163398150514),
        name: 'language',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4524813516878528973),
        name: 'imageBytes',
        type: 23,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7437051840820766456),
        name: 'processingTimeMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2132836910663006502),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 3869265884307842858),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [3114669513764623696],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      4488856207737410458,
      6799473932462299156,
      3909429294942409669,
      3600695220137962669,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    FilterResultModel: obx_int.EntityDefinition<FilterResultModel>(
      model: _entities[0],
      toOneRelations: (FilterResultModel object) => [],
      toManyRelations: (FilterResultModel object) => {},
      getId: (FilterResultModel object) => object.id,
      setId: (FilterResultModel object, int id) {
        object.id = id;
      },
      objectToFB: (FilterResultModel object, fb.Builder fbb) {
        final languageOffset = fbb.writeString(object.language);
        final imageBytesOffset = fbb.writeListInt8(object.imageBytes);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, languageOffset);
        fbb.addOffset(2, imageBytesOffset);
        fbb.addInt64(3, object.processingTimeMs);
        fbb.addInt64(4, object.timestamp.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final languageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final imageBytesParam =
            const fb.Uint8ListReader(
                  lazy: false,
                ).vTableGet(buffer, rootOffset, 8, Uint8List(0))
                as Uint8List;
        final processingTimeMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = FilterResultModel(
          id: idParam,
          language: languageParam,
          timestamp: timestampParam,
          imageBytes: imageBytesParam,
          processingTimeMs: processingTimeMsParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [FilterResultModel] entity fields to define ObjectBox queries.
class FilterResultModel_ {
  /// See [FilterResultModel.id].
  static final id = obx.QueryIntegerProperty<FilterResultModel>(
    _entities[0].properties[0],
  );

  /// See [FilterResultModel.language].
  static final language = obx.QueryStringProperty<FilterResultModel>(
    _entities[0].properties[1],
  );

  /// See [FilterResultModel.imageBytes].
  static final imageBytes = obx.QueryByteVectorProperty<FilterResultModel>(
    _entities[0].properties[2],
  );

  /// See [FilterResultModel.processingTimeMs].
  static final processingTimeMs = obx.QueryIntegerProperty<FilterResultModel>(
    _entities[0].properties[3],
  );

  /// See [FilterResultModel.timestamp].
  static final timestamp = obx.QueryDateProperty<FilterResultModel>(
    _entities[0].properties[4],
  );
}
